"""make index, doc_id, text and vector non-nullable

Revision ID: 349450ca327d
Revises: 6968f0f8d392
Create Date: 2026-07-05 08:11:35.239269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = '349450ca327d'
down_revision: Union[str, Sequence[str], None] = '6968f0f8d392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedding', 'doc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('embedding', 'index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('embedding', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('embedding', 'vector',
               existing_type=VECTOR(dim=1536),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedding', 'vector',
               existing_type=VECTOR(dim=1536),
               nullable=True)
    op.alter_column('embedding', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('embedding', 'index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('embedding', 'doc_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
