"""add Document and Embedding

Revision ID: 6968f0f8d392
Revises: 
Create Date: 2026-06-25 11:54:12.473776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = '6968f0f8d392'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable the pgvector extension in PostgreSQL
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    # Define the exact enum object
    documentstatus_enum = postgresql.ENUM('PENDING', 'PROGRESS', 'PAUSED', 'CANCELED', 'COMPLETED', 'FAILED', name='documentstatus')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'PROGRESS', 'PAUSED', 'CANCELED', 'COMPLETED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_hash'), 'document', ['hash'], unique=False)
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_document_public_id'), 'document', ['public_id'], unique=True)
    op.create_table('embedding',
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('vector', VECTOR(dim=1536), nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_embedding_vector', 'embedding', ['vector'], unique=False, postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
    op.create_index(op.f('ix_embedding_doc_id'), 'embedding', ['doc_id'], unique=False)
    op.create_index(op.f('ix_embedding_id'), 'embedding', ['id'], unique=False)
    op.create_index(op.f('ix_embedding_public_id'), 'embedding', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_public_id'), table_name='embedding')
    op.drop_index(op.f('ix_embedding_id'), table_name='embedding')
    op.drop_index(op.f('ix_embedding_doc_id'), table_name='embedding')
    op.drop_index('idx_embedding_vector', table_name='embedding', postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
    op.drop_table('embedding')
    op.drop_index(op.f('ix_document_public_id'), table_name='document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_index(op.f('ix_document_hash'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
