"""fix bugs in embedding model

Revision ID: dc9dd9def5d5
Revises: f70b9d5bd973
Create Date: 2026-06-24 10:33:07.477321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9dd9def5d5'
down_revision: Union[str, Sequence[str], None] = 'f70b9d5bd973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
